simulation:
  total_steps: 250
  boundary_condition: "periodic"
  save_evolution: True
  save_images: True

probs:
  dist_type: "uniform"
  seed: 42
  p_neutral: 0.1    
  p_chiral: 0.1
  p_copy: 0.8

chaos:
  mode: "constant"

  constant:
    epsilon: 1.0

  pulse:
    start_step: 40
    end_step: 50
    magnitude: 5.0

  linear:
    start_epsilon: 0.0
    end_epsilon: 1.0
